server:
  port: 8073
  
eureka:
  client:
    service-url:
     default-zone: http://localhost:8761/
     
#spring:
#  datasource:
#   username: root
#   url: jdbc:mysql://localhost:3306/easyservicedb
#   password: root
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  application:
#   name: WORKER-SERVICE
spring:
  application:
    name: WORKER-SERVICE
  config:
    import: configserver:http://localhost:8888